name: Build
on:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup Java 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '11'
            -   name: Grant Permissions to gradlew
                run: chmod +x gradlew
            -   name: Build with Gradle
                run: ./gradlew build
